#!/bin/bash

./locate_services.py

#set -m
#./mitmdump -p 9000 -M '|https://package.elm-lang.org/|http://localhost:3000/v1/' >/dev/null 2>&1 &

#sleep 1s

#https_proxy=http://127.0.0.1:9000 \
#REQUESTS_CA_BUNDLE=~/.mitmproxy/mitmproxy-ca-cert.pem \
./build_elm.py

#trap "killall mitmdump" EXIT
