#!/bin/bash

set -m
./mitmdump -p 9000 -M '|https://package.elm-lang.org/|http://localhost:3000/v1/' >/dev/null 2>&1 &

sleep 1s

cp ~/.mitmproxy/mitmproxy-ca-cert.pem .

openssl x509 -in mitmproxy-ca-cert.pem -inform PEM -out mitmproxy-ca-cert.crt

mkdir /usr/share/ca-certificates/extra
cp mitmproxy-ca-cert.crt /usr/local/share/ca-certificates/
update-ca-certificates

trap "killall mitmdump" EXIT
